### PR TITLE
Fixed README.md typo error

### PR DESCRIPTION
**Pull request by tapanprakasht**
Fix the typo error in README.md mentioned in the #180 by @madsonic
Method signature gave the README.md was wrong

### CODE REVIEW

**Comment by letsgogeeky** [comment]
It doesn't require the `name:` while passing the argument since it's a single parameter function.

**Comment by tapanprakasht** [comment]
@letsgogeeky without name: parameter it is giving an error. It looks like parameter is needed. I tried with Swift 3

**Comment by letsgogeeky** [comment]
Yeah got it! with swift 3 it's required!

**Comment by buba447** [comment]
Can you make a note about swift 3? @tapanprakasht

**Pull request merged**
