### PR TITLE
Set minimum iOS version to 9.0 for project and Package.swift

### PR DESCRIPTION
**Pull request by eneko**
While the [iOS framework target has its minimum version required set to iOS 9.0](https://github.com/airbnb/lottie-ios/blob/531eb22d47a9439a2344fdaf96832189f2c6e925/Lottie.xcodeproj/project.pbxproj#L2355), both the project and `Package.swift` were set to iOS 12.0.

This update allows for Lottie to be used via SwiftPM on iOS 9 projects.

### CODE REVIEW

**Comment by gabrielPeart** [comment]
Yes, is not a good idea to drop support for older iOS versions at the time, even more when the library works just fine in older iOS (I currently use Lottie on iOS 11 targets and works just fine)

**Comment by danielsaidi** [comment]
@StatusQuo @Dschee Is there any reason for the package file to require iOS 12? We can run it perfectly well in iOS 11, using @eneko s `master` branch.

**Comment by StatusQuo** [comment]
sell also #1010

**Comment by eneko** [comment]
@StatusQuo how can we get this landed? It's been almost two months :)

**Comment by StatusQuo** [comment]
@eneko well idk. I would instantly merge this request to fix this inconsistency of podspec and swift-package but I don’t have the privileges to do this 😅 Iam working on another pull request to enable macOS via spm maybe this one would push the topic again

**Comment by buba447** [comment]
Hey everyone! Sorry for the delay, I'm the maintainer of Lottie. Ive been super busy on a few other projects the past few months. Ill merge this now though. Feel free to reach out in the future.

Godspeed,
Brandon
brandon@withrow.io

**Comment by eneko** [comment]
Thank you @buba447 👏

**Comment by danielsaidi** [comment]
Perfect, thanks all! Will it be released as a 3.1.3?

**Pull request merged**
