### PR TITLE
Use warn instead of assertionFailure when detecting repeater use

### PR DESCRIPTION
**Pull request by AlexanderKvamme**
This is based on a fix discussed in https://github.com/airbnb/lottie-ios/issues/1739

### CODE REVIEW

**Comment by AlexanderKvamme** [comment]
@calda Was this what you ment? This is my first open source contribution so be gentle 😅

**Comment by calda** [comment]
Fixes #1739

**Comment by shollington-rbi** [comment]
@calda - is it possible to get a point release available on cocoapods with this fix?

**Comment by calda** [comment]
Sure, I'll release a new version soon.

**Comment by shollington-rbi** [comment]
That would be amazing, thank you so much @calda .

**Comment by calda** [comment]
Released 3.4.4 with this change today

**Comment by shollington-rbi** [comment]
Thanks so much @calda . :)

**Pull request merged**
