### PR TITLE
fix keypath traversal

### PR DESCRIPTION
**Pull request by RolandasRazma**
correct me if I'm wrong, but I think layer by key path lookup is wrong

### CODE REVIEW

**Comment by RolandasRazma** [comment]
if this PR is correct, wonder about https://github.com/airbnb/lottie-ios/blob/master/lottie-swift/src/Private/Utility/Extensions/AnimationKeypathExtension.swift#L75 - that looks wrong as well

**Comment by jonasman** [comment]
I confirm this fixes the keypath issue

**Review by jonasman — APPROVED** [review]

**Comment by RolandasRazma** [comment]
what about https://github.com/airbnb/lottie-ios/pull/1156#issuecomment-604274077

**Review by isimpson — APPROVED** [review]
This definitely fixes an issue when adding subviews to a Keypaths using:
`public func addSubview(_ subview: AnimationSubview, forLayerAt keypath: AnimationKeypath)`

Can we please have this merged and released asap.

**Review by isimpson — APPROVED** [review]

**Comment by isimpson** [comment]
@thedrick do you think this fix could be merged as its blocking us using that latest release?

**Comment by calda** [comment]
This seems like a reasonable change. To merge this, I think we'd need to:
 1. Rebase and resolve merge conflicts
 2. Add a test case to the regression suite. You can add animation JSON files to `Tests/Samples`, and configure `AnimationKeypath`s for the test case [here](https://github.com/airbnb/lottie-ios/blob/master/Tests/SnapshotConfiguration.swift#L42).

I'm closing this PR because it's gone stale, but feel free to rebase and re-open after making updates.

**Comment by isimpson** [comment]
Seems to have been fixed here: https://github.com/airbnb/lottie-ios/pull/1587

**Pull request closed without merging**
