### PR TITLE
Update of readme to mention last supported version of objective c

### PR DESCRIPTION
**Pull request by matthewdovey**
This PR updates the README file to mention the last version of Lottie that supports Objective-C to help users with older projects or users starting new Objective-C projects that wish to import Lottie.

### CODE REVIEW

**Comment by buba447** [comment]
There is still an active branch that offers objective c support. This branch is kept alive to maintain objective c and mainly for bug fixes.
The official objective c branch can be found here: https://github.com/airbnb/lottie-ios/tree/lottie/objectiveC
Also check out the documentation regarding it here: http://airbnb.io/lottie/#/ios-migration

It would probably help a lot to also mention that branch.

**Comment by matthewdovey** [comment]
I have added the links to the migration document and the active Objective-C branch. Let me know if this looks okay.

**Comment by CRGTCRGT** [comment]
can use swift version bridge to Objective-c?

**Comment by cherishloveyou** [comment]
can use swift version bridge to Objective-c?

**Pull request merged**
