### PR TITLE
Remove a few unused imports

### PR DESCRIPTION
**Pull request by hanton**
Follow up with #2246 to fix CI failure related to Xcode 14.1 / Swift 5.6

### CODE REVIEW

**Comment by hanton** [comment]
cc: @calda

**Review by calda — APPROVED** [review]
Thanks

**Comment by hanton** [comment]
Thank you for highlighting this matter. I apologize for any inconvenience caused! I have a theory about what might be causing this issue, but as I was unable to replicate it in Xcode 15.1, I'm uncertain if the changes I've made will resolve it. Could you please provide further details on how to repro the issue? Specifically, is there a need to use a particular version of Xcode, or are specific Schemas required?

**Comment by calda** [comment]
Interestingly I can't seem to reproduce this in Xcode, but I can reproduce it when I run this command from our `Rakefile` on the command line:

```
$ bundle exec rake build:xcframework
```

**Pull request merged**
