### PR TITLE
Add nullability annotation

### PR DESCRIPTION
**Pull request by punty**
Remove warnings when using the latest version of the pod

### CODE REVIEW

**Comment by punty** [comment]
Is lottie still active?

**Comment by Quarezz** [comment]
+1

**Comment by jvisenti** [comment]
I'm also seeing warnings in `LOTAnimationView` for these methods:
```obj-c
+ (instancetype)animationFromJSON:(NSDictionary *)animationJSON inBundle:(NSBundle *)bundle NS_SWIFT_NAME(init(json:bundle:));
+ (instancetype)animationWithFilePath:(NSString *)filePath NS_SWIFT_NAME(init(filePath:));
```

**Comment by shawnwall** [comment]
+1

**Pull request closed without merging**
