### PR TITLE
Improve compatibility with Swift Package Manager for iOS

### PR DESCRIPTION
**Pull request by daveanderson**
Does not resolve the inability to do a Swift Package Manager build for macOS but is a step in the right direction.

### CODE REVIEW

**Comment by daveanderson** [comment]
Similar to #939 but does not change the locations of files

**Comment by buba447** [comment]
Hey @daveanderson sorry Im just now getting around to looking at this! First, thanks for your help contributing to Lottie!

So whats the right path forward with this. Im not familiar with Swift Package Manager, is there no way to occlude files from the build based on platform?

**Comment by StatusQuo** [comment]
Hi @buba447 no actually if os annotation is only available in source files.

**Comment by donnywdavis** [comment]
If you could separate the files into different targets then you could exclude based on platform. Then you would just have to do the file level `#if` annotations for shared code. Here's an example of how `Quick` does that, https://github.com/Quick/Quick/blob/master/Package.swift. Sorry if not relevant, just saw the example and and wanted to mention it. 🙂

**Pull request merged**
