### PR TITLE
Fix for storyboard crash

### PR DESCRIPTION
**Pull request by buba447**
Fixes a storyboard agent crash when initializing an AnimationView from storyboard.

### CODE REVIEW

**Comment by kaannesinn** [comment]
@buba447 Is this change on the Lottie's 3.0.1 pod version? Because when I update to 3.0.1 and want to use AnimationView class on our storyboard as an outlet, app crashes. (saying AnimationView class from Interface builder isnt known)

**Comment by buba447** [comment]
@kaannesinn This is in 3.0.1. Did you set the module for the AnimationView to Lottie?

**Comment by buba447** [comment]
@kaannesinn I found another crash in the Interface Builder and put a fix up here https://github.com/airbnb/lottie-ios/pull/808
Hopefully that fixes the issues. These interface builder crashes are hard to debug since there is no crash logs. Test it out and please open a new issue if you continue experiencing a crash so i can look into it!

**Comment by kaannesinn** [comment]
@buba447 ok I have updated to the master branch with the issue #789 and now set the module to Lottie. Now crash disappeared while try to show the animation view. Thanks :)

I am using the last commit with your new fix #808 . I will track it again and tell you if I see a new crash with that, ok.

**Pull request merged**
