### PR TITLE
Check type to avoid app crash.

### PR DESCRIPTION
**Pull request by Brsoyan**

### CODE REVIEW

**Comment by buba447** [comment]
Im not sure how this avoids a crash as the type should be enforced by the method declaration.

**Comment by Brsoyan** [comment]
NSURL and NSString  subclass of NSObject and both confirm to protocols <NSCopying, NSMutableCopying, NSSecureCoding>.  When you set NSString by mistake, compile time we received only warning and we can build and run our app. After that app is crashed.

**Comment by buba447** [comment]
I see. I would actually prefer an assert instead of just letting the function continue incorrectly. Either way crashing is the expected behavior here.

**Comment by Brsoyan** [comment]
Ok I Agree.

**Pull request closed without merging**
