### PR TITLE
Work Around Xcode 12 Beta 1 Compilation Issues

### PR DESCRIPTION
**Pull request by danl3v**
Fixes a compilation issue while archiving on Xcode 12 Beta 1

### CODE REVIEW

**Comment by museum-future** [comment]
Unless this fix works with other versions of xcode, i would not pull this into the main branch.  This patch needs to be explicity defined for xcode 12+

**Comment by danl3v** [comment]
Hi @museum-future. Thanks for taking a look! `Substring` has the same interface as `String`, so the behavior will be the same for prior versions. `Substring` just provides a memory optimization. See https://developer.apple.com/documentation/swift/substring

That said, happy to wrap the patch up if you like

**Comment by agiokas** [comment]
It would be great if this PR would get reviewed and merged.

**Comment by danl3v** [comment]
No idea! Someone from Airbnb needs to approve and merge it!

**Comment by buba447** [comment]
Lgtm thanks for grabbing this!

**Comment by danl3v** [comment]
It is possible in a future xcode beta that these changes will be unnecessary. Will open a revert if this is the case down the line

**Pull request merged**
