### PR TITLE
CI Build Integration

### PR DESCRIPTION
**Pull request by ferico55**
With this PR, I am trying to add build verification on CI
The CI of choice is `Bitrise`. No affiliation whatsoever it is because bitrise offers free plan.

The CI will validates
- iOS library build
- maOS Catalyst library build
- macOS library build
- tvOS library build
- static rules checking using `Danger`
Feel free to tweak and change the workflow, the steps etc thru `bitrise.yml` and `Fastfile`

**need help:** Need admin of this repo to register the webhook to Bitrise

next thing to do: visual regression test

Previews:
Bitrise logs summary
Screen Shot 2021-05-07 at 21 13 23

Bitrise build triggered via PR webhooks
Screen Shot 2021-05-07 at 22 14 06

Github checks
Screen Shot 2021-05-07 at 22 14 38

### CODE REVIEW

**Comment by ferico55** [comment]
and for this to work, I need a branch in the main repo with the configs in it. But sadly I do not have access to push or create branch on main repo, so this will not work until this PR is merged, so see it in action in a PR, take a look [here](https://github.com/ferico55/lottie-ios/pull/2)

**Comment by buba447** [comment]
This is great! What do I need to do to set things up on my end?

**Comment by ferico55** [comment]
first, we will need the `bitrise.yml` to exists on the main repo (no need to be in master, can be in any branch)
I also invited you to the bitrise app for our repo as an admin - please check your email.

then we can setup the WebHook from GitHub to Bitrise. we have 2 options
#### 1. use SSH key
go to `settings` tab in bitrise app config [url here](https://app.bitrise.io/app/59ffc7574570cf7c#/settings).
Screen Shot 2021-05-15 at 15 23 03
choose `Change SSH Keypair` under `SSH Settings` section. this is to replace my pre-configured ssh key to yours. then I'll do the rest (re-configure the webhooks)

#### 2. setup manually (in case you are not comfortable setting up your GitHub SSH key to Bitrise)
go to the `code` settings in bitrise app config [url here](https://app.bitrise.io/app/59ffc7574570cf7c#/code).
Screen Shot 2021-05-15 at 15 21 31
change the `Incoming Webhooks` setting to manual and follow the instructions (here)[https://github.com/bitrise-io/bitrise-webhooks#github---setup--usage]

alternative option: grant me temporary admin access to the repo, I'll set it up and you can revoke the access later. I'm not sure if you're comfortable with this, so laying all the options on the table

**Comment by thedrick** [comment]
This is awesome work and definitely needed! I'm wondering if we should actually use [Github actions](https://github.com/airbnb/lottie-ios/actions/new) as they provide free CI for open source projects (and it's what we use for our other open source projects at Airbnb)

**Comment by calda** [comment]
Thank you for this suggestion. Resolved by #1427.

**Pull request closed without merging**
