### PR TITLE
Fix frame setting issue for CompatibleAnimationView.

### PR DESCRIPTION
**Pull request by snow-google**
As discussed on the GitHub page in the past, CompatibleAnimationView does not correctly set up the constaints as to make the underlying AnimationView fill the entirity of the frame provided to CompatibleAnimationView. https://github.com/airbnb/lottie-ios/issues/1091

This fix is the same that was discussed in the issue thread and resolves the frame setting issue.

### CODE REVIEW

**Comment by calda** [comment]
I don't think this change is backwards-compatible, it seems like it could easily be a breaking change for consumers who have code that relies on `translatesAutoresizingMaskIntoConstraints` defaulting to `false`. Could you share more details about your issue? Why does this fix the problem? Is there another solution we could use that would have less effect on existing consumers?

**Comment by snow-google** [comment]
As it is, the compatible view is a wrapper on the underlying animation view. When the compatible view has its frame set, the underlying animation view does not get these updates. This is not a problem when using the aniamtion view directly which means that it is only ObjC compatible views that have this unexpected behavior. In essense, the abstraction and encapsulation that the compatible view is supposed to create are broken by the current behavior which requires compatible view users to investigate how to resolve the issue. It is possible that the workaround previously discussed on this forum makes it less likely for people to report this issue, but for my use case, overriding the value in our source code is incredibly challenging.

**Review by calda — APPROVED** [review]
Ok, thanks for the explanation. I think this change makes sense considering `translatesAutoresizingMaskIntoConstraints` also defaults to `true` for `LottieAnimationView` -- seems like we'd want both to have the same behavior.

I went ahead and also added a test case for `CompatibleAnimationView` to the snapshot test suite.

**Comment by snow-google** [comment]
Thank you so much for the work to accept and verify this change! I appreciate the responsiveness of the team!

**Pull request merged**
