### PR TITLE
Add helper method to load animation on view loaded in Interface Builder

### PR DESCRIPTION
**Pull request by Xeaza**
Refers to issue #512

### CODE REVIEW

**Comment by Xeaza** [comment]
I didn't update the example app to use this method because I couldn't think of a good place for it to go. If you think it's worth doing, let me know and I'll find a place.

**Comment by buba447** [comment]
Great! Thanks for grabbing this! This will be in the pending 2.5 release.

**Comment by rockylive** [comment]
Can you please release this fix to cocoa pods

**Comment by fadylateef** [comment]
any new updates !

**Pull request merged**
