### PR TITLE
Add privacy manifest

### PR DESCRIPTION
**Pull request by OhJaeBeen**
Since we are still using Objective-C, we need to apply the privacy manifest. Therefore, I would appreciate it if you could approve it.
thank you

### CODE REVIEW

**Comment by OhJaeBeen** [comment]
Thank you so much

2024년 4월 5일 (금) 오전 9:37, Cal Stephens ***@***.***>님이 작성:

**Comment by calda** [comment]
Np thanks for the PR

**Comment by TigerWf** [comment]
**pod 'lottie-ios', :git => 'https://github.com/airbnb/lottie-ios.git', :branch => 'lottie/objectiveC'**

I didn't find "PrivacyInfo.xcprivacy" after pod install. Do you also need to modify "lottie-ios.podspec"?

**Comment by OhJaeBeen** [comment]
hello
Even if you change to the objectC branch and do not date,
The privacyinfo file is not visible.
How can I solve this?
thank you

2024년 4월 5일 (금) 오전 9:49, Cal Stephens ***@***.***>님이 작성:

**Comment by OhJaeBeen** [comment]
Unfortunately I still can't see it

**Comment by TigerWf** [comment]
I think you should  modify the "lottie-ios.podspec" file, add the following code :
s.resource_bundles = {
'LottiePrivacyInfo' => [‘Lottie/PrivacyInfo.xcprivacy'],
}
then post a new PR again.  @OhJaeBeen

**Comment by OhJaeBeen** [comment]
thank you
It had to be modified once again due to a quote issue.
I would like to request PR again.

**Pull request merged**
